name: Salesforce Deploy on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Salesforce CLI plugins
        run: |
          npm install -g sfdx-cli

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        run: |
          echo "sfdx --version"
          echo ${{ secrets.CONSUMER_KEY }} | base64 --decode > /tmp/server.key
          echo ${{ secrets.DECRYPTION_KEY }} | base64 --decode > /tmp/dec.key
          echo ${{ secrets.DECRYPTION_IV }} | base64 --decode > /tmp/dec.iv
          sfdx force:auth:jwt:grant -u ${{ secrets.USERNAME }} -f /tmp/server.key -i $CONSUMER_KEY -s -d -r https://login.salesforce.com -k /tmp/dec.key -v devhub

      - name: Deploy on Salesforce
        run: |
          # The path to your source directory
          SOURCE_DIR="force-app"

          # Run the deployment command
          sfdx force:source:deploy --targetusername ${{ secrets.USERNAME }} --manifest ../../manifest/package.xml --checkonly --wait 10 --testlevel RunLocalTests