name: Salesforce Validate QA on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install Salesforce CLI plugins
        run: |
          npm install -g sfdx-cli

      - name: Set up Salesforce CLI
        run: |
          sfdx force:auth:jwt:grant --username "${{secrets.USERNAME_QA}}" --jwtkeyfile "${{secrets.JWT_KEY_FILE}}" --clientid "${{secrets.CONSUMER_KEY_QA}}" -r https://login.salesforce.com --setdefaultdevhubusername

      - name: Deploy on Salesforce
        run: |
          # The path to your source directory
          SOURCE_DIR="force-app"

          # Run the deployment command
          sfdx force:source:deploy --targetusername ${{ secrets.USERNAME_QA }} --manifest "manifest/package.xml" --checkonly --wait 10 --testlevel NoTestRun